title: Experience AI Challenge | Stage 2 | Text Classifier
hero_image: images/banner.png
description: Create your own text classifier machine learning model that can ID heros and villians from their words alone!
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduction
  - title: Create a machine learning model
  - title: Train the model
  - title: Make a Scratch application
  - title: What next?
